### ISSUE TITLE
Repo niceties

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/ui-seeds#40]
As Seeds starts to mature, there are some additional details we should add to the repo. For example:

- [ ] Readme with getting started instructions
- [ ] License (Apache?)

**Updated:** to be discussed separately:

- [ ] Changelog -- see: https://github.com/semantic-release/changelog
- [ ] `package.json` isn't updating with latest release version -- see: https://github.com/semantic-release/git

**Comment by jaredcwhite** [comment]
**Added:** I was confused looking at `package.json` in the repo and still seeing `0.1.0`. It seems like the release process is bumping up versions but not creating commits of updating that file. ui-components also seems to have that issue (right now you look at `package.json` and it's 7.2.2 even those the latest release is 12.x)

**Comment by jaredcwhite** [comment]
On the changelog thing, I suppose we could just link to GitHub releases where stuff it getting captured automatically:

https://github.com/bloom-housing/ui-seeds/releases

**Comment by jaredcwhite** [comment]
Question: on the "to be discussed separately" points, should we create issue(s) for them? Do we still want to discuss them?

**Comment by sarahlazarich** [comment]
@jaredcwhite you can create issues! Is this tickey good to go otherwise

**Comment by sarahlazarich** [comment]
per slack, closing
